# Generated by Django 3.2.9 on 2021-11-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_conf', models.IntegerField()),
                ('total_death_toll', models.IntegerField()),
                ('day_conf', models.IntegerField()),
                ('day_death', models.IntegerField()),
                ('total_critical_rate', models.FloatField(null=True)),
                ('first_death', models.IntegerField()),
                ('first_conf', models.IntegerField()),
                ('first_ciritical_rate', models.FloatField(null=True)),
                ('second_death', models.IntegerField()),
                ('second_conf', models.IntegerField()),
                ('second_ciritical_rate', models.FloatField(null=True)),
                ('third_death', models.IntegerField()),
                ('third_conf', models.IntegerField()),
                ('third_ciritical_rate', models.FloatField(null=True)),
            ],
        ),
    ]
