# Generated by Django 3.2.9 on 2021-11-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_totaldata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalData',
        ),
    ]
